### ISSUE TITLE
Change section text

### ISSUE THREAD

**Issue by ialberquilla** [Libree/Libree_Landing2_M#7]
Change the text of this section for the new one

![Image](https://github.com/Libree/Libree_Landing2_M/assets/974720/159211c5-6eb0-4188-bc21-1e529e0ed011)

The button should link to our discord server

**Comment by ialberquilla** [comment]
I think Teresa sent you this new image. Can you also change it?

**Comment by Pedrocaloi** [comment]
> I think Teresa sent you this new image. Can you also change it?

Yep no problem
